---
title: "ESM204-Assignment3"
author: "Geoffrey Cook"
date: "5/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Reading in Libraries and Databases}
##############################################################
# Reading in libraries and databases
##############################################################

# Libraries
library(tidyverse)
library(car)
library(RColorBrewer)
library(stargazer)
library(vcdExtra)
library(reshape2)
library(effsize)
library(pwr)
library(kableExtra)
library(corrplot) 
library(janitor)
library(lubridate) 
library(gganimate)
library(ggimage)
library(plotly)

# Data
whales <- read_csv("HW3Data.csv")

```

```{r Question 1}
##############################################################
# Question 1
##############################################################
# Create a linear probability model that predicts a respondent’s probability of voting ‘yes’ on the ballot based on their age, income, NEP score, the risk reduction offered by the program, and the cost of the program to that respondent. Show the model and interpret the regression coefficients
##############################################################

# Probability of voting 'YES'
### Not sure if all we need to have here are the coefficients but if so, this seems to give those to us.

p_yes <- lm(vote ~ age+income+NEP+risk+bid, data = whales)
p_yes

summary(p_yes)
```
```{r Question 2}
##############################################################
# Question 2
##############################################################
# Based on this regression, what can you say about the value of a single prevented whale death? (Hint: Think about how risk reduction for all whales translates into the number of whale deaths avoided)
##############################################################


```

